Harjoitus 5
=======
Harjoituksen tarkoitus
-----------
Harjoituksen tarkoituksena on testata Django verkkokehyksen toimivuutta kehitysvaiheessa ja tuotannossa.

Aloitetaan tekemällä webbisovellus, jolla on simppeli CRUD. Opetuskerran aikana ehdinkin jo asentaa virtuaaliympäristön ja luoda oman projektin. Requiremenets teksitiedostoon määritellään asennettava paketti (Django), jotta pip osaa sentaa sen. Pip on työväline Python-pakettien asennukseen.


>sudo apt-get install virtualenv (asennetaan virtuaaliympäristö)
>
>virtualenv --system-site-packages -p python3 env/ (luodaan uusi virtuaaliympäristö)
>
>source env/bin/activate (käynnistetään virtuaaliympäristö)
>
>micro requirements.txt Django (määritellään asennettavat Python-paketit)
>
>pip install requirements.txt (asennetaan paketit)
>
>django-admin startproject sampsaco (aloitetaan uusi projekti)
>
>./manage.py runserver (testataan toimiiko; kyllä toimii)
>
>./manage.py startapp appointments (tehdään uusi tietokanta ajanvarauksille)
>
>micro sampsaco/settings.py (käydään lisäämässä kanta projektin määrityksiin)
>
>micro crm/appointments.py (lisätään luokka, sille attribuutit description, client, strattime, endtime) 
>
>./manage.py makemigrations & ./manage.py migrate (lisätään luokkiin tehdyt muutokset tietokantaan)
>
>micro appointments/admin.py (rekisteröitään tietokanta, jotta se näkyy /admin endpointissa)

Käydäänpä katsomassa näkyykö Appointments taulu sovelluksessamme. Navigoidaan siis localhost/admin ja kirjaudutaan sisään tunnilla luoduilla tunnuksilla. Admin tunnukset luotiin komennolla ./manage.py createsuperuser. 

![Image](/django/appointments1.png "404")
![Image](/django/appointments2.png "404")

Kyllä, kanta toimii eikä sen luomisessa ilmennyt yhtään ongelmia. Lisäsin kantaan myös yhden testitapaamisen ja se näyttää sen ilman ongelmia.

![Image](/django/appointments3.png "404")

Tietueen nimi on kannassa kuitenkin 'Appointment object (1)' ja tätähän me emme halua. Käydäänpä siis muuttamassa Appointment luokan palautuslauseketta. Navigoitaan taas models.py tiedostoon ja lisätään sinne funktio joka palauttaa tapaamisen kuvauksen ja ajankohdan. Huomasin myös, että aikaisemmin unohdin lisätä date-attribuutin, ja käytössäni oli vain kellonajat. Lisätään mukaan siis date attribuutti, importataan Pythonin datetime (from datetime import datetime) ja laitetaan sovellus palauttamaan tapaamisen kuvaus ja aika.

>def __str__(self):
>        return self.description + ' Päivä: ' +  self.date.strftime("%D")

![Image](/django/appointments4.png "404")

Nyt palautus näyttää järkevämmältä! Seuraavaksi lisätään pari käyttäjää.

## Käyttäjät


## Lähteet:
* https://www.geeksforgeeks.org/datetimefield-django-models/?ref=lbp
* https://appdividend.com/2022/02/02/how-to-convert-datetime-to-string-in-python/
* https://terokarvinen.com/2022/django-instant-crm-tutorial/
* https://terokarvinen.com/2021/linux-palvelimet-ict4tn021-3018/#h5